#pragma once

#define INTERACTIVE_WALLPAPER_VERSION_MAJOR 0
#define INTERACTIVE_WALLPAPER_VERSION_MINOR 2
#define INTERACTIVE_WALLPAPER_VERSION_PATCH 0
#define INTERACTIVE_WALLPAPER_VERSION_STRING L"0.2.0"
